# Coordinate creation and area selection

## dcm2angle

In [53]:
import numpy as np

def dcm2angle(R, sequence):
    if sequence == 'ZYX':
        theta1 = np.arctan2(R[1, 2], R[2, 2])
        theta2 = np.arcsin(-R[0, 2])
        theta3 = np.arctan2(R[0, 1], R[0, 0])
        return theta1, theta2, theta3
    if sequence == 'XYZ':
        theta1 = np.arctan2(R[2, 1], R[2, 2])
        theta2 = np.arcsin(-R[2, 0])
        theta3 = np.arctan2(R[1, 0], R[0, 0])
        return theta1, theta2, theta3
    elif sequence == 'ZYX':
        theta1 = np.arctan2(R[1, 0], R[0, 0])
        theta2 = np.arcsin(-R[2, 0])
        theta3 = np.arctan2(R[2, 1], R[2, 2])
        return theta1, theta2, theta3
    else:
        raise ValueError("Invalid sequence")

# Example usage
R = np.array([[1, 0, 0],
              [0, 1, 0],
              [0, 0, 1]])

sequence = 'ZYX'
angles = dcm2angle(R, sequence)
print(angles)


(0.0, 0.0, 0.0)


In [54]:
lmn= np.array([[0.5,0.090524305,0.861281226],
               [-0.06041,0.995745059,-0.069586667],
               [-0.86392,-0.017237422,0.503341182]])
              
sequence = 'ZYX'
angles = dcm2angle(lmn, sequence)
print(np.degrees(angles))

#  rad2deg (yaw)
#  rad2deg (pitch)
#  rad2deg (roll

[ -7.87121863 -59.46074466  10.26215846]


In [13]:
lmn[1, 2]

-0.069586667

In [14]:
lmn[2, 2]

0.503341182

## ZYX

### Rz theta3

In [48]:
np.degrees(np.arctan2( 0.090524305,0.5))

10.262158460538497

In [49]:
np.degrees(np.arctan2(-.06041,0.995745059)) #xxxxxxxxxxxxx

-3.471773079020504

### Ry theta2

In [50]:
np.degrees(np.arcsin(-0.861281226))  #yyyyyyyyyyyyyyyy

-59.46074466244338

In [51]:
np.degrees(np.arctan2(-0.861281226,0.5))  #yxxxxxxxxxx

-59.86352887252943

In [52]:
np.degrees(np.arctan2(-0.86392,0.503341182))   #yxxxxxxxxxx

-59.77386314156867

### Rx theta1

```
! RZ = ATAN2(x_m,x_l)
! RY = ASIN(-x_n)
! RX = ATAN2(y_n,z_n)
! CLOCAL, CSN, 0, X_0, Y_0, Z_0, RZ, RY, RX
```

## ZXY

In [3]:
import numpy as np

def dcm2angle(R, sequence):
    if sequence == 'ZYX':
        Rx = np.arctan2(R[1, 2], R[2, 2])
        Ry = np.arcsin(-R[0, 2])
        Rz = np.arctan2(R[0, 1], R[0, 0])
        return theta1, theta2, theta3
    if sequence == 'XYZ':
        theta1 = np.arctan2(R[2, 1], R[2, 2])
        theta2 = np.arcsin(-R[2, 0])
        theta3 = np.arctan2(R[1, 0], R[0, 0])
        return theta1, theta2, theta3
    elif sequence == 'ZXY':
        theta1 = np.arctan2(-R[0, 2], R[2, 2])
        theta2 = np.arcsin(R[1, 2])
        theta3 = np.arctan2(-R[1, 0], R[1, 1])
        return theta2,theta1 ,theta3
    else:
        raise ValueError("Invalid sequence")

# Example usage
R = np.array([[1, 0, 0],
              [0, 1, 0],
              [0, 0, 1]])

sequence = 'ZXY'
angles = dcm2angle(R, sequence)
print(angles)

(0.0, 0.0, 0.0)


In [4]:
lmn= np.array([[0.5,0.090524305,0.861281226],
               [-0.06041,0.995745059,-0.069586667],
               [-0.86392,-0.017237422,0.503341182]])
              
sequence = 'ZXY'
angles = dcm2angle(lmn, sequence)
print(np.degrees(angles))

#  rad2deg (yaw)
#  rad2deg (pitch)
#  rad2deg (roll

[ -3.99024709 -59.69756667   3.47177308]


In [5]:
np.degrees(np.arctan2(-(-0.06041),0.995745059))

3.471773079020504

In [6]:
np.degrees(np.arcsin(-0.069586667))

-3.990247090487281

In [7]:
np.degrees(np.arctan2(-(0.861281226),0.503341182))

-59.69756667484733

In [8]:
lmn= np.array([[0.001,0,0], [0,0.00099,-0.0001],[0,0.0001,0.00099]])
              
sequence = 'ZXY'
angles = dcm2angle(lmn, sequence)
print(np.degrees(angles))

#  rad2deg (yaw)
#  rad2deg (pitch)
#  rad2deg (roll

[-0.00572958 -0.         -0.        ]


```
RZ = ATAN2(-y_l,y_m)
RX = ASIN(y_n)
RY = ATAN2(-x_n,z_n)

CLOCAL, CSN, 0, X_0, Y_0, Z_0, RZ, RX, RY

```

## XYZ

In [30]:
import numpy as np

def dcm2angle(R, sequence):
    if sequence == 'ZYX':
        Rx = np.arctan2(R[1, 2], R[2, 2])
        Ry = np.arcsin(-R[0, 2])
        Rz = np.arctan2(R[0, 1], R[0, 0])
        return Rx, Ry, Rz
    if sequence == 'XYZ':
        Rx = np.arctan2(-R[2, 1], R[2, 2])
        Ry = np.arcsin(R[2, 0])
        Rz = np.arctan2(-R[1, 0], R[0, 0])
        return Rx, Ry, Rz
    elif sequence == 'ZXY':
        Ry = np.arctan2(-R[0, 2], R[2, 2])
        Rx = np.arcsin(R[1, 2])
        Rz = np.arctan2(-R[1, 0], R[1, 1])
        return Rx, Ry ,Rz
    else:
        raise ValueError("This sequence not available")

# Example usage
R = np.array([[1, 0, 0],
              [0, 1, 0],
              [0, 0, 1]])

sequence = 'ZXY'
angles = dcm2angle(R, sequence)
print(angles)

(0.0, 0.0, 0.0)


In [31]:
lmn= np.array([[0.5,0.090524305,0.861281226],
               [-0.06041,0.995745059,-0.069586667],
               [-0.86392,-0.017237422,0.503341182]])
              
sequence = 'XYZ'
angles = dcm2angle(lmn, sequence)
print(np.degrees(angles))

[  1.96138473 -59.75961124   6.8890845 ]


In [32]:
np.degrees(np.arctan2(-(-0.017237422),0.503341182))

1.9613847281871681

In [33]:
np.degrees(np.arcsin(-0.86392))

-59.75961123795097

In [34]:
np.degrees(np.arctan2(-(-0.06041),0.5))

6.889084504860569

In [9]:
 lmn= np.array([[1, 0, 0 ],
                [0, 0.994521895368273, -0.104528463267654 ],
                [0, 0.104528463267654, 0.994521895368273]])
    
sequence = 'ZXY'
angles = dcm2angle(lmn, sequence)
print(np.degrees(angles))    

[-6. -0. -0.]


In [ ]:
import numpy as np

def dcm2angle(R, sequence):
    if sequence == 'ZYX':
        Rx = np.arctan2(R[1, 2], R[2, 2])
        Ry = np.arcsin(-R[0, 2])
        Rz = np.arctan2(R[0, 1], R[0, 0])
        return Rx, Ry, Rz
    if sequence == 'XYZ':
        Rx = np.arctan2(-R[2, 1], R[2, 2])
        Ry = np.arcsin(R[2, 0])
        Rz = np.arctan2(-R[1, 0], R[0, 0])
        return Rx, Ry, Rz
    elif sequence == 'ZXY':
        Ry = np.arctan2(-R[0, 2], R[2, 2])
        Rx = np.arcsin(R[1, 2])
        Rz = np.arctan2(-R[1, 0], R[1, 1])
        return Rx, Ry ,Rz
    else:
        raise ValueError("This sequence not available")

# Example usage
R = np.array([[1, 0, 0],
              [0, 1, 0],
              [0, 0, 1]])

sequence = 'ZXY'
angles = dcm2angle(R, sequence)
print(angles)

In [74]:
order='YZX'
MatDict = {char: ord(char) for char in order}
    
MatDict['X'] = 0
MatDict['Y'] = 1
MatDict['Z'] = 2
    
keys = list(MatDict.keys())
    
a = MatDict[keys[0]]
b = MatDict[keys[1]]
c = MatDict[keys[2]]

print(a,b,c)

1 2 0


## Final

In [151]:
import numpy as np

def dcm2rotation(R, sequence="XYZ"):
    
    """
    Converts a Direction Cosine Matrix (DCM) to Euler angles.

    Parameters:
        R (numpy.ndarray): 3x3 rotation matrix representing the DCM.
        sequence (str): String specifying the desired rotation sequence. Defaults to 'TXYZ'.
                        

    Returns:
        tuple: Tuple of three Euler angles (theta1, theta2, theta3) in radians.

    Raises:
        TypeError: If an invalid sequence is provided. Implemented for "XYZ","ZXY","YZX","ZYX","YXZ","XZY" only
        
    Notes:
        - The function uses the numpy library for array operations and trigonometric functions.

    """
    
    available = ["XYZ","ZXY","YZX","ZYX","YXZ","XZY"] 
    avail_posi = ["XYZ","ZXY","YZX"]
    
    if sequence in available:
        i= -1 if sequence in avail_posi else 1
        
        MatDict = {char: ord(char) for char in sequence}

        MatDict['X'] = 0
        MatDict['Y'] = 1
        MatDict['Z'] = 2

        keys = list(MatDict.keys())

        a = MatDict[keys[0]]
        b = MatDict[keys[1]]
        c = MatDict[keys[2]] 

        R1 = np.arctan2(i*R[c, b], R[c, c])
        R2 = np.arcsin(i*-R[c, a])
        R3 = np.arctan2(i*R[b, a], R[a, a])

        return R1, R2, R3
    else:
        raise TypeError('Sorry,Implemented for this sequence only "XYZ","ZXY","YZX","ZYX","YXZ","XZY"')
        
if __name__ == '__main__':

    lmn= np.array([[0.5,0.090524305,0.861281226],
               [-0.06041,0.995745059,-0.069586667],
               [-0.86392,-0.017237422,0.503341182]])
              
    sequence = 'XYZ'
    angles = dcm2rotation(lmn, sequence)
    print(np.degrees(angles)) 


[  1.96138473 -59.75961124   6.8890845 ]


In [152]:
print(dcm2rotation.__doc__)


    Converts a Direction Cosine Matrix (DCM) to Euler angles.

    Parameters:
        R (numpy.ndarray): 3x3 rotation matrix representing the DCM.
        sequence (str): String specifying the desired rotation sequence. Valid options are 'ZYX', 'XYZ', and 'ZYX'.

    Returns:
        tuple: Tuple of three Euler angles (theta1, theta2, theta3) in radians.

    Raises:
        TypeError: If an invalid sequence is provided.

    Notes:
        - The function uses the numpy library for array operations and trigonometric functions.

    


In [153]:
lmn= np.array([[0.5,0.090524305,0.861281226],
               [-0.06041,0.995745059,-0.069586667],
               [-0.86392,-0.017237422,0.503341182]])
              
sequence = 'XYZ'
angles = dcm2rotation(lmn, sequence)
print(np.degrees(angles))

[  1.96138473 -59.75961124   6.8890845 ]


In [155]:
lmn= np.array([[0.5,0.090524305,0.861281226],
               [-0.06041,0.995745059,-0.069586667],
               [-0.86392,-0.017237422,0.503341182]])

angles = dcm2rotation(lmn)
print(np.degrees(angles))

[  1.96138473 -59.75961124   6.8890845 ]


In [154]:
sequenc = 'ZXY'
angles = dcm2rotation(lmn, sequenc)
print(np.degrees(angles))

[  3.47177308  -3.99024709 -59.69756667]


In [145]:
sequence = 'ZYX'
angles = dcm2rotation(lmn, sequence)
print(np.degrees(angles))

[ 10.26215846 -59.46074466  -7.87121863]


In [146]:
sequence = 'ZFX'
angles = dcm2rotation(lmn, sequence)
print(np.degrees(angles))

TypeError: Sorry,Implemented for this sequence only "XYZ","ZXY","YZX","ZYX","YXZ","XZY"

In [105]:
check_collinear = lambda p1, p2, p3: (p2[0] - p1[0]) * (p3[1] - p1[1]) == (p3[0] - p1[0]) * (p2[1] - p1[1]) and \
                                     (p2[1] - p1[1]) * (p3[2] - p1[2]) == (p3[1] - p1[1]) * (p2[2] - p1[2]) and \
                                     (p2[2] - p1[2]) * (p3[0] - p1[0]) == (p3[2] - p1[2]) * (p2[0] - p1[0])

# Example usage
p1 = (0, 0, 0)
p2 = (1, 1, 1)
p3 = (5, 5, 5)

if check_collinear(p1, p2, p3):
    print("Points are collinear")
else:
    print("Points are not collinear")


Points are not collinear


---

## Contact area detection

### Coordinate creation

In [279]:
import numpy as np

In [280]:
check_collinear = lambda p1, p2, p3: np.linalg.norm(np.cross((p2-p1), (p1-p3))) 

In [281]:
dcv = lambda x, y, z: np.array([x / np.sqrt(x**2 + y**2 + z**2),
                                y / np.sqrt(x**2 + y**2 + z**2),
                                z / np.sqrt(x**2 + y**2 + z**2)])

In [282]:
def coordinate_dcm(origin,p1,p2):
    
    if abs(check_collinear(origin,p1,p2)) < 1.0e-6:
        
        print("Points are collinear, Select largest line and create a kp")
        
    else:
        
        v1= p1- origin                 #vector-1
        v2= p2- origin                 #vector-2
        v1_dc=dcv(v1[0],v1[1],v1[2])
        v2_dc=dcv(v2[0],v2[1],v2[2])

        v3=np.cross(v1_dc, v2_dc)      #vector-3, perp to 1,2
        v3_dc=dcv(v3[0],v3[1],v3[2])  

        v4=np.cross(v3_dc, v1_dc)      #vector-4(y) perp vector-3(z) perp to vector-1(x)
        v4_dc=dcv(v4[0],v4[1],v4[2])

        return v1_dc, v4_dc, v3_dc

In [283]:
def dcm2angleZXY(R):
    
    Ry = np.arctan2(-R[0, 2], R[2, 2])
    Rx = np.arcsin(R[1, 2])
    Rz = np.arctan2(-R[1, 0], R[1, 1])
    
    return Rx, Ry ,Rz

**Example**

In [293]:
origin=np.array([10,50,10])
p1=np.array([10,10,11])
p2=np.array([5,5,15])

if check_collinear(origin,p1,p2)==0:
    print("Points are collinear, Select largest line and create a kp")
    
else:
    xl,yl,zl=coordinate_dcm(origin,p1,p2)
    print(xl)
    print(yl)
    print(zl)

[ 0.         -0.99968765  0.02499219]
[-0.7905077   0.01530652  0.6122608 ]
[-0.6124521  -0.01975652 -0.79026078]


In [294]:
R = np.array([[xl[0], yl[0], zl[0]],
              [xl[1], yl[1], zl[1]],
              [xl[2], yl[2], zl[2]]])
R

array([[ 0.        , -0.7905077 , -0.6124521 ],
       [-0.99968765,  0.01530652, -0.01975652],
       [ 0.02499219,  0.6122608 , -0.79026078]])

In [295]:
R=np.column_stack((xl, yl, zl))
R

array([[ 0.        , -0.7905077 , -0.6124521 ],
       [-0.99968765,  0.01530652, -0.01975652],
       [ 0.02499219,  0.6122608 , -0.79026078]])

In [296]:
# R = np.array([[xl[0], yl[0], zl[0]],
#               [xl[1], yl[1], zl[1]],
#               [xl[2], yl[2], zl[2]]])

R=np.column_stack((xl, yl, zl))

angles = dcm2angleZXY(R)
print(angles)

(-0.01975780494578869, 2.4822825852569355, 1.555486220526841)


### Check 4th point in plane

In [297]:
check_coplaner = lambda p1, p2, p3, p4: np.linalg.det(np.array([ [p1[0], p2[0], p3[0], p4[0]],
                                                                  [p1[1], p2[1], p3[1], p4[1]],
                                                                  [p1[2], p2[2], p3[2], p4[2]],
                                                                  [1,     1,      1,     1  ] ]))



**Example**

In [179]:
p1= np.array([0, 0, 0])
p2= np.array([1, 0, 0])
p3= np.array([0, 1, 0])
p4= np.array([0, 0, 0])


if abs(check_coplaner(p1, p2, p3, p4)) < 1.0e-6:
    print("PLANE")
else:
    print("Not plane")


PLANE


### Find center of circle from three point 

https://stackoverflow.com/questions/20314306/find-arc-circle-equation-given-three-points-in-space-3d

https://mathworld.wolfram.com/BarycentricCoordinates.html

https://mathworld.wolfram.com/Circumcenter.html

https://mathworld.wolfram.com/Circumcircle.html

https://github.com/sergarrido/random/tree/master/circle3d

https://new.math.uiuc.edu/public403/affine/bary.html

In [265]:
def circle_center_radius(A, B, C):

    if abs(check_collinear(A,B,C)) < 1.0e-6:      
        raise ValueError("Points are collinear, no unique circle exists.")
    
    a = np.linalg.norm(C - B)
    b = np.linalg.norm(C - A)
    c = np.linalg.norm(B - A)
    
    s = (a + b + c) / 2
    rad = a*b*c / 4 / np.sqrt(s * (s - a) * (s - b) * (s - c))
    
     #Barycentric Coordinates of circumsnter
    b1 = a*a * (b*b + c*c - a*a)
    b2 = b*b * (a*a + c*c - b*b)
    b3 = c*c * (a*a + b*b - c*c)     
    
     #Barycentric Coordinates to cartesian Coordinates 
    centr = def circle_center_radius(A, B, C):

    if abs(check_collinear(A,B,C)) < 1.0e-6:      
        raise ValueError("Points are collinear, no unique circle exists.")
    
    a = np.linalg.norm(C - B)
    b = np.linalg.norm(C - A)
    c = np.linalg.norm(B - A)
    
    s = (a + b + c) / 2
    rad = a*b*c / 4 / np.sqrt(s * (s - a) * (s - b) * (s - c))
    
     #Barycentric Coordinates of circumsnter
    b1 = a*a * (b*b + c*c - a*a)
    b2 = b*b * (a*a + c*c - b*b)
    b3 = c*c * (a*a + b*b - c*c)     
    
     #Barycentric Coordinates to cartesian Coordinates 
    centr = np.column_stack((A, B, C)).dot(np.hstack((b1, b2, b3)))  
    centr /= b1 + b2 + b3
#     centr = centr/(b1 + b2 + b3)
    
    return centr,rad.dot(np.hstack((b1, b2, b3)))  
    centr /= b1 + b2 + b3
#     centr = centr/(b1 + b2 + b3)
    
    return centr,rad


**Example**

In [266]:
point1 = np.array([1, 1, 0])
point2 = np.array([1, -1, 0])
point3 = np.array([-1, 1, 0])

Center,Radius=circle_center_radius(point1, point2, point3)
print(Center)
print(Radius)

# point1.dot((2,2,2))

[-2.22044605e-16 -2.22044605e-16  0.00000000e+00]
1.4142135623730958


In [268]:
# Points are collinear

point1 = np.array([1, 2, 3])
point2 = np.array([4, 5, 6])
point3 = np.array([7, 8, 9])

Center,Radius=circle_center_radius(point1, point2, point3)
print(Center)
print(Radius)

ValueError: Points are collinear, no unique circle exists.