In [1]:
# cent=[372.071067811865, -90, 217.071067811865]
# P1=[363.232233047034, -102.5, 208.232233047034]
# P2= [380.909902576697, -77.5, 225.909902576697]
import numpy as np

In [2]:
import sys
PYTHONTOOLSDIR = r'C:\Users\pramod.kumar\OneDrive - SIEMENSGAMESA\Work\ContactDetect'
sys.path.append(PYTHONTOOLSDIR)
import ContactDetection as cd

In [3]:
# print(cd.check_normal.__doc__)

In [4]:
# print(cd.check_collinear.__doc__)

In [5]:
# print(cd.check_coplaner.__doc__)

In [6]:
# print(cd.dcv.__doc__)

In [7]:
# print(cd.check_normal.__doc__)

```
name :FACE1_INTF1_cIR
Area :490.873852123405
Perimeter :78.5398163397448
Type: 22
point: x= 372.071067811865 y= -90 z= 217.071067811865
dir:   i= 0.707106781186547 j= 0 k= 0.707106781186548
box:   x= 363.232233047034 y= -102.5 z= 208.232233047034 a= 380.909902576697 b= -77.5 c= 225.909902576697
radius: 0
rad_data : 0
nor
```m_dir : 1

In [34]:
# z_norm=np.array([0.707106781186547, 0, 0.707106781186548])
z_norm= np.array([0,1,1])


In [35]:
y_norm,x_norm=cd.perpendicular_vector(z_norm)

In [36]:
xl= cd.dcv(x_norm[0],x_norm[1],x_norm[2])
yl= cd.dcv(y_norm[0],y_norm[1],y_norm[2])
zl= cd.dcv(z_norm[0],z_norm[1],z_norm[1])
zl

array([nan, nan, nan])

In [32]:
R=np.array([xl,yl,zl])
R

array([[ 1.,  0.,  0.],
       [ 0.,  1.,  0.],
       [nan, nan, nan]])

In [12]:
Rx,Ry,Rz=cd.dcm2angleZXY(R)

In [13]:
print(Rx,"\n",Ry,"\n",Rz)

0.0 
 50.76847951640772 
 -0.0


CLOCAL, CS_Index, 0, 372.071067811865/1000,-90/1000,217.0710678/1000   
,0Z,50X,0Y

In [44]:
import sys
import numpy as np
PYTHONTOOLSDIR = r'C:\Users\pramod.kumar\OneDrive - SIEMENSGAMESA\Work\ContactDetect'
sys.path.append(PYTHONTOOLSDIR)
import ContactDetection as cd
def get_rotation(z_norm):
    y_norm,x_norm=cd.perpendicular_vector(z_norm)
    # print(y_norm)
    # print(x_norm)
    xl= cd.dcv(x_norm[0],x_norm[1],x_norm[2])
    yl= cd.dcv(y_norm[0],y_norm[1],y_norm[2])
    zl= cd.dcv(z_norm[0],z_norm[1],z_norm[2])
    R=np.array([xl,yl,zl])
    Rx,Ry,Rz=cd.dcm2angleZXY(R)
    return Rz, Rx, Ry 

```
name :FACE1_INTF1_cIR
Area :490.873852123405
Perimeter :78.5398163397448
Type: 22
point: x= 372.071067811865 y= -90 z= 217.071067811865
dir:   i= 0.707106781186547 j= 0 k= 0.707106781186548
box:   x= 363.232233047034 y= -102.5 z= 208.232233047034 a= 380.909902576697 b= -77.5 c= 225.909902576697
radius: 0
rad_data : 0
nor
```m_dir : 1

In [38]:
z_norm= np.array([0.707106781186547, 0, 0.707106781186548])
get_rotation(z_norm)

[0. 1. 0.]
[ 0.70710678  0.         -0.70710678]


(-0.0, 0.0, 44.999999999999964)

```
name :FACE2_INTF1_sQ
Area :288
Perimeter :68
Type: 22
point: x= 312.674098192195 y= -88 z= 276.468037431535
dir:   i= 0.707106781186547 j= 0 k= 0.707106781186548
box:   x= 307.017243942703 y= -97 z= 270.811183182043 a= 318.330952441688 b= -79 c= 282.124891681028
radius: 0
rad_data : 0
norm_dir : 1
```

In [39]:
z_norm= np.array([0.707106781186547,0 ,0.707106781186548])
get_rotation(z_norm)

[0. 1. 0.]
[ 0.70710678  0.         -0.70710678]


(-0.0, 0.0, 44.999999999999964)

```
name :ft
Area :9221.1261478766
Perimeter :646.539816339745
Type: 22
point: x= 365 y= 0 z= 220
dir:   i= 0 j= 0 k= 1
box:   x= 265 y= -25 z= 220 a= 465 b= 25 c= 220
radius: 0
rad_data : 0
norm_dir : 1
```

In [40]:
z_norm= np.array([0,0,1])
get_rotation(z_norm)

[0. 1. 0.]
[1. 0. 0.]


(-0.0, 0.0, -0.0)

```
name :FACE4_INTF1
Area :1164.92010597476
Perimeter :116.492010597476
Type: 16
point: x= 46 y= 85 z= 230
dir:   i= 2.77555756156289E-17 j= 0.5 k= -0.866025403784439
box:   x= 33.3367537296533 y= 69.0333070355012 z= 215.008122826982 a= 58.6632462703467 b= 100.966692964499 c= 244.991877173018
radius: 9.2701396586509
rad_data : 0
norm_dir : -1
```

In [43]:
z_norm=np.array([2.77555756156289E-17, 0.5, -0.866025403784439])
get_rotation(z_norm)

[ 0.        -0.8660254 -0.5      ]
[ 1.00000000e+00 -1.38777878e-17  2.40370336e-17]


(-180.0, -29.999999999999993, -180.0)

```
name :FACE1_INTF1
Area :490.873852123405
Perimeter :78.5398163397448
Type: 22
point: x= 369.095760221445 y= 149.26423563649 z= 217.094064799162
dir:   i= 0.409576022144496 j= -0.573576436351046 k= 0.709406479916223
box:   x= 356.443669460417 y= 135.656829516929 z= 205.784977599803 a= 381.747850982474 b= 162.87164175605 c= 228.403151998522
radius: 0
rad_data : 0
norm_dir : 1
```

In [45]:
z_norm=np.array([0.409576022144496 ,-0.573576436351046, 0.709406479916223])
get_rotation(z_norm)

(0.0, 38.95657940063204, 24.17820395979116)